### ISSUE TITLE
Looking forward...

### ISSUE THREAD

**Issue by wilixx** [yulequan/PU-Net#1]
Today I wander around and get here but only a read-me file presented in this place. I am far away from totally understanding the papers your team published, hopefully I can still get some ideas. Looking forward to your code. Thanks for the open source spirit.

**Comment by yulequan** [comment]
Hi, I have uploaded the training and testing code.

**Comment by suhangpro** [comment]
Awesome work! 
Your paper points to supp. material for many details. Is it possible to make it also available?

**Comment by yulequan** [comment]
Hi, you can find the supp material in http://appsrv.cse.cuhk.edu.hk/~lqyu/papers/CVPR18_PUNet_supp.pdf
