### ISSUE TITLE
Make error for evaluation.cpp

### ISSUE THREAD

**Issue by ghost** [yulequan/PU-Net#10]
I installed CGAL from [this link](https://www.cgal.org/download/linux.html) as instructed by Readme.md, however, I have the error all the time no matter how I manually add missing files to the corresponding directory: `/kj/Documents/PU-Net-modify/evaluation_code/evaluation.cpp:19:50: fatal error: CGAL/Polygon_mesh_processing/measure.h: No such file or directory
`
Anyone is having this issue?

**Comment by yulequan** [comment]
Maybe you need to build from source when installing CGAL.

**Comment by ghost** [comment]
> Maybe you need to build from source when installing CGAL.

After manually deleting all `*cgal*` files under `usr` directory and `sudo apt-get remove libcgal-dev`, and source installing CGAL, I am able to run this code. 
Thanks!
