### ISSUE TITLE
libtensorflow_framework.so

### ISSUE THREAD

**Issue by junhaozhang98** [yulequan/PU-Net#11]
Hi,Where did this “”libtensorflow_framework.so”file come from?Is it a c++ version compiled from the TensorFlow source code? Need to compile it by myself? Because, i could not locate this file.

**Comment by yulequan** [comment]
It is in the tensorflow library. It should be in the folder where the tensorflow is installed.

**Comment by junhaozhang98** [comment]
Thank you very much! Is there any difference between installing directly with "pip install tensorflow-gpu" and using bazel to build?Does this have an effect on compiling TF operators?
