### ISSUE TITLE
About the NUC calculation

### ISSUE THREAD

**Issue by jialancong** [yulequan/PU-Net#14]
Hi, 

thanks for openning your code ! I am wondering how to get .off file used in Evaluation code ?

Thank you !

**Comment by yulequan** [comment]
You can download the training and testing mesh files from https://drive.google.com/file/d/1lp2HWU78tx_-tz8cxE8PSxb-M7ZQCMOq/view

**Comment by jialancong** [comment]
Thank you very much！

**Comment by jialancong** [comment]
@yulequan
Hi Lequan,

Is the dataset mentioned in " Table 1. Quantitative comparison on our collected dataset. " in your paper coming from the test folder downloading by https://drive.google.com/file/d/1lp2HWU78tx_-tz8cxE8PSxb-M7ZQCMOq/view ？

BTW, after I got the density.xyz, I found some of the values are very big, such as 250.575 125.525 83.8792 63.0406 50.57 42.275 33.955 which made NUC big. And In each xxx_density.xyz there contains values around 250. But in xxx.xyz file I didn't find such big coordinate value.

**Comment by yulequan** [comment]
Yes, the model in Table 1 is the testing model on google drive.

The values in XXXX_density.xyz should be  n^k_i/(N^k*p).  So it should not be very ball.

**Comment by jialancong** [comment]
But the big values of XXXX_density.xyz make NUC big . In your paper, NUC is calculated by weighted sum of square(n^k_i/(N^k*p)). Since the n^k_i/(N^k*p) can be big, after square(), it becomes bigger. 

Therefore, I can't get NUC value under 1 as " Table 1. Quantitative comparison on our collected dataset. " show. What's more, every XXX_density.xyz has such big values. I don't know why. Can you tell me how to get NUC value under 1 ? Thank you !

**Comment by yulequan** [comment]
The values in XXX_density.xyz should around 1. You can first use the input point set ('https://github.com/yulequan/PU-Net/tree/master/data/test_data/our_collected_data/MC_5k') to calculate the density to see the range of the values.

**Comment by jialancong** [comment]
I tested camel.xyz just now, and got several values around 10~20 in camel_density.xyz

**Comment by yulequan** [comment]
It is strange. I just tested the camel too. But the result seems reasonable. BTW, the NUC is the std of these values.

[camel_density.txt](https://github.com/yulequan/PU-Net/files/2653275/camel_density.txt)

**Comment by jialancong** [comment]
It is strange....orz.
I tested again using p=40, got following values in density.xyz, when I set p=9000, I can get more values over 10.
0.5 0.6 0.6 0.7 0.77 0.75 0.78 
0.35 0.5 0.516667 0.55 0.56 0.558333 0.56 
0.4 0.425 0.5 0.5 0.52 0.583333 0.78 
0.5 0.4 0.333333 0.3125 0.37 0.366667 0.38 
0.5 0.35 0.333333 0.3625 0.35 0.375 0.386667 
0.45 0.65 0.8 0.975 1.13 1.05 0.953333 
0.2 0.5 0.483333 0.4375 0.52 0.5 0.48 
0.55 0.625 0.75 0.75 0.8 0.766667 1.16667 
0.5 0.375 0.4 0.375 0.37 0.408333 0.406667 
0.7 0.625 0.55 0.6125 0.58 0.625 0.666667 
0.55 0.475 0.4 0.3625 0.36 0.366667 0.34 
1.05 0.925 2 1.6375 1.63 1.91667 3.12667 
0.55 0.75 0.633333 0.6125 0.67 0.708333 0.76 
1.2 1.175 1.38333 1.55 1.64 1.60833 1.64 
0.7 0.8 0.833333 0.8625 0.92 0.85 0.886667 
0.25 0.35 0.4 0.4 0.45 0.45 0.48 
3.75 2 1.38333 1.1125 0.92 0.791667 0.733333 
1.65 1.575 1.5 1.6 1.63 1.59167 1.52 
0.25 0.4 0.366667 0.3875 0.46 0.458333 0.56 
0.2 0.4 0.4 0.45 0.49 0.575 0.54 
2.65 1.875 1.61667 1.4 1.22 1.1 0.973333 
5 3.175 2.55 2.375 2.07 1.90833 1.89333 
0.7 1.175 1.21667 1.075 1.05 1.04167 1.01333 
0.45 0.5 0.483333 0.4625 0.47 0.441667 0.486667 
0.8 0.85 0.95 0.8125 0.83 0.866667 0.873333 
1.4 1.6 1.33333 1.1875 1.18 1.10833 0.993333 
0.55 0.525 0.566667 0.575 0.61 0.583333 0.546667 
0.35 0.425 0.433333 0.475 0.48 0.5 0.546667 
0.45 0.6 0.683333 0.6625 0.69 0.75 0.68 
1.05 0.925 0.833333 0.7875 0.8 0.775 0.726667 
0.6 0.575 0.6 0.55 0.52 0.533333 0.533333 
0.25 0.35 0.35 0.35 0.35 0.333333 0.353333 
0.5 0.525 0.533333 0.575 0.58 0.533333 0.52 
0.5 0.5 0.6 0.6125 0.6 0.591667 0.593333 
0.4 0.475 0.45 0.4875 0.59 0.583333 0.7 
0.35 0.475 0.533333 0.55 0.53 0.55 0.586667 
0.75 0.575 0.566667 0.525 0.52 0.525 0.533333 
0.65 0.525 0.583333 0.5625 0.64 0.775 0.84 
0.65 0.6 0.5 0.5 0.5 0.458333 0.48 
10.85 6.275 4.28333 3.325 2.76 2.35 2.00667

**Comment by jialancong** [comment]
Thank you to test again for me !

I downloaded the data and evaluation code again. After using new data and code, I still got several values around 10~20 in each XXX_density.xyz with p=9000
This is the code(camel.xyz and camel.off) and data I used.

[data.zip](https://github.com/yulequan/PU-Net/files/2653963/data.zip)
[code.zip](https://github.com/yulequan/PU-Net/files/2654001/code.zip)

**Comment by yulequan** [comment]
What is the std deviation of these values?

**Comment by jialancong** [comment]
[camel_point2mesh_distance_xyz.txt](https://github.com/yulequan/PU-Net/files/2655571/camel_point2mesh_distance_xyz.txt)

This is point2mesh_distance.xyz file I got.

**Comment by jialancong** [comment]
The avg and std deviation of these values are :
```
AVG= [ 0.96034444  0.94496944  0.93532223  0.93160833  0.92906778  0.92756666
  0.9250526 ]
std_dev= [ 108.85178883   81.86912798   68.80970174   61.84862393   56.77856883
   53.22897074   49.4893919 ]
```

This is my code calculating avg and std :
[calc_density_py.txt](https://github.com/yulequan/PU-Net/files/2655657/calc_density_py.txt)

The data I use come from https://github.com/yulequan/PU-Net/tree/master/data/test_data/our_collected_data/MC_5k (for .xyz file) and https://drive.google.com/file/d/1lp2HWU78tx_-tz8cxE8PSxb-M7ZQCMOq/view  (for mesh file).

BTW, I trained and evaluated the model  again following the Usage 3 and 4. Then I evaluated the results it got and still found some big values around 250. But when I use the .xyz file from https://github.com/yulequan/PU-Net/tree/master/data/test_data/our_collected_data/MC_5k the big values descrease to 10. I don't know why...

**Comment by jialancong** [comment]
@yulequan If I want to reproduce the results in your paper, I only need to set THREAD be 900. Is that right  ?

**Comment by yulequan** [comment]
THREAD is the number of thread in multi-thread programming. It can not be
900..... You need to change the number of disks that each thread handles.

**Comment by jialancong** [comment]
Got it, change line 223: `for (int i=0;i<THREAD*10;i++)` to  `for (int i=0;i<THREAD*900;i++)` . Right?

**Comment by yulequan** [comment]
Yes. Or you can change the THREAD according to the number of CPU core in
your computer.

**Comment by jialancong** [comment]
Thank you ~!
