### ISSUE TITLE
question about NUC

### ISSUE THREAD

**Issue by fuckmeagain** [yulequan/PU-Net#15]
hi! @yulequan I was confused about the output of density.xyz file.Is the value in the file the final nuc value? I tried to calculate the values of several models and the values mentioned in the paper are quite different.

**Comment by fuckmeagain** [comment]
@yulequan  Thank you for your reply. I got how to calculate the NUC value.

**Comment by jialancong** [comment]
@yulequan Hi, I am still confusing about the density.xyz. Why there are seven column in density.xyz ? while I was expecting one column which is n^k_i/(N^k*p) of one certain disk.

**Comment by fuckmeagain** [comment]
@jialancong  In evaluation.cpp file contain senven different radius, such as 0.002 0.004 util to 0.015. So the first column is correspond 0.002

**Comment by yulequan** [comment]
In evaluation.cpp file contain senven different radius, such as 0.002 0.004 util to 0.015. So the first column is correspond 0.002

**Comment by jialancong** [comment]
I got it. Thank you ! @yulequan

**Comment by jialancong** [comment]
Hi! @fuckmeagain The values in your XXX_density.xyz are all under 1 ? I always find some big values in my XXX_density.xyz。
