### ISSUE TITLE
Mesh file of training

### ISSUE THREAD

**Issue by jialancong** [yulequan/PU-Net#16]
Hi, @yulequan . Can you provide the mesh file you used for training (for cropping patches) ? Thank you !

In PU-Net supp, you mentioned the name of mesh file you used for training. But I can't find the specific .off file in Visionair repository (http://visionair.ge.imati.cnr.it/ontologies/shapes/search.jsp).  For example , when I search Armadillo, it shows 10 kind of Armadillo. And for the 'Boy1' mentioned in PU-Net supp, there are no results were found.

**Comment by yulequan** [comment]
They are also in the google drive. It contains the training meshes and testing meshes.

**Comment by jialancong** [comment]
Oh! I missed it orz... Thank you again !
