### ISSUE TITLE
MeshSegmentation.exe missing

### ISSUE THREAD

**Issue by Lotayou** [yulequan/PU-Net#20]
Hi @yulequan , I cannot find MeshSegmentation.exe as mentioned in `./prepare_data/MeshSegmentation/ReadMe.txt'. Can you upload a compiled exe or show me how to compile the source code? Thanks

**Comment by yulequan** [comment]
The meshviewer.cpp is the only main file. Besides that, it also contains a library "eigen3" and our own library "mesh". I think you can easily create a vs project to compile the code. :)

**Comment by ptxaxx** [comment]
@yulequan @Lotayou Could you share the details of the implementation？
I encountered  a problem：
![image](https://user-images.githubusercontent.com/94749768/196135168-2b55b455-4d92-4b60-8056-08bcf520d73c.png)
