### ISSUE TITLE
Prepare dataset for variable sized input

### ISSUE THREAD

**Issue by dattanand** [yulequan/PU-Net#23]
Hi,
I am trying to create a dataset which can give me upsampled point cloud of 5000 points, I plan to create new dataset with input size of 5000/4 points. My queries are,

1. Using mesh segmentation, how many patches do I need create? 
2.  how many points need to be sampled using poisson disk sampling. I guess these numbers would vary based on input size.
3. How do I write them in .H5, basically, what will be my input format and size of input?

If you mention precise executing instructions for poisson sampling and writing into HDF will be greatly helpful

thanks

**Comment by yulequan** [comment]
Hi,
1. When I use the mesh segmentation to extract N patches from a mesh, I only empirically set N=10. Therefore, there is no hard rule about the number of patches in a mesh.

2. In our experiments, we sample 4K points from a patch without considering the size of the patches. 

3.  In the h5 file, I save the points coordinates (x,y,z) of each patch. So there is an NX4096X3 array, where N is the number of patches in the dataset. (I forget if I also save the normal vector for each point. If so, the size should be NX4096X6)

**Comment by mdane-x** [comment]
@dattanand  How did you manage to build MeshSegmentation tool for creating patches?

**Comment by ptxaxx** [comment]
@dattanand How did you manage to build MeshSegmentation tool for creating patches?
