### ISSUE TITLE
Hi, appreciate your excellent work. And I have a question that, where can I find the code that extract the pathes from point clouds,

### ISSUE THREAD

**Issue by Leerw** [yulequan/PU-Net#27]
Described in your paper:

> From each selected point, we grow a surface patch on the object, such that any point on the patch is within a certain geodesic distance (d) from the selected point over the surface.  ground truth point distribution on the patch.

**Comment by yulequan** [comment]
You can find the code in this folder. https://github.com/yulequan/PU-Net/tree/master/prepare_data
However, the code is not fully organized.
