### ISSUE TITLE
PdSampling_nofix Utility?

### ISSUE THREAD

**Issue by gtmtg** [yulequan/PU-Net#4]
Hi! I'm interested in re-training PU-Net on a new dataset and I'm currently trying to figure out how to perform patch extraction on my meshes to generate training data for the network. I saw that the current codebases calls a utility called `PdSampling_nofix` (referenced on line 134 of `code/utils/modelnet_data_prep.py`). However, I Googled around a bit and couldn't find this/a similar tool for performing Poission disk sampling on a mesh—any pointers on where I might be able to find the `PdSampling_nofix` tool you used?

**Comment by yulequan** [comment]
The code in 'utils' is not well organized. The "PdSampling_nofix" is the name of our own written program. We use the VCG library (http://vcg.isti.cnr.it/vcglib/) to do Poisson disk sampling.
