### ISSUE TITLE
how to downsample huge model

### ISSUE THREAD

**Issue by yo-ting-shieh** [yulequan/PU-Net#6]

**Comment by yo-ting-shieh** [comment]
how to downsample huge model, e.g. 10k -> 4k points

**Comment by yulequan** [comment]
We randomly choose the 4K points from the 10k points. You can refer to the `nonuniform_sampling ` function in the data_provider.py file.

**Comment by yo-ting-shieh** [comment]
If i want to training a new model myself, which data format should i prepare and which folder should i put them in. I found many folders path in modelnet_data_prep.py ,but i had no idea what should i put into each folder and those are not including in this git project.
