### ISSUE TITLE
EMD loss

### ISSUE THREAD

**Issue by shumink** [yulequan/PU-Net#7]
HI Lequan,

In your code base I can see that there's source code for the ops for emd loss. However I can't find it from the original author's github repo. Is the emd loss written by you or by contacting the original author?

Asking because I'm getting a weird bug for using your EMD loss. When I pass the output tensor from my network into the emd loss as is, I get an CUDA_ERROR_ILLEGAL_ADDRESS error. This error doesn't exist when I simply pass in two reference ground truth points cloud. The original author mentioned in the paper that he/she implemented an approximation for this loss, I'm not sure whether this is the root cause.

Thanks,
Shumin

**Comment by yulequan** [comment]
Hi, this EMD loss is written by the original author. It works fine if the output points are less than 4096 points.

**Comment by shumink** [comment]
@yulequan I was passing 1024 points in.. Guess I'll have to debug myself. Thanks anyway.
