### ISSUE TITLE
model preparation

### ISSUE THREAD

**Issue by yo-ting-shieh** [yulequan/PU-Net#8]
Hi,

If i want to training a new model myself, which data format should i prepare and which folder should i put them in. I found many folders path in modelnet_data_prep.py ,but i had no idea what should i put into each folder and those are not including in this git project.

Thanks,

**Comment by yulequan** [comment]
Hi, it is a little complex if you want to train the model with your own dataset. The basic pipeline is: 

1) dividing the mesh model into different patches. (We find approximate geodesic patches with ring-by-ring manner)
2) sampling 4096 points from each patch with "Poisson disk sampling method"
3) saving the sampled points into hdf5 file. 

Currently, these code is not in this git project. I will clean the code and release them as soon as possible. 
FYI, we use the "Poisson disk sampling" method in VCGlib (http://vcg.isti.cnr.it/vcglib/). The "Poisson disk sampling" method in Meshlab is also based on this library.

**Comment by yo-ting-shieh** [comment]
@yulequan thanks for you provide the basic pipeline, i'll try this work as u advice.
I'm curious to know how u dividing the mesh model into different patches,had u did this step in PU-Net? or dividing just in your new work(EC-Net)?
very thanks for your help :)

**Comment by yulequan** [comment]
In PU-Net, we only divide the meshes into different patches in the training phase. This is because that we divide the patches in mesh level and we do not have ground truth mesh in the testing phase.

In EC-Net, we divide the point clouds into patches in both the training and testing phases. This is done in point cloud level via knn graphes.

**Comment by yo-ting-shieh** [comment]
@yulequan For the process you mentioned above, i still have some questions:

1. dividing the mesh(ring-by-ring manner),need dividing 100 patches for every mesh?(e.g. mesh_1~100).
Are these patches any order?
2. for each patches sampling 4096 points, what if each patches or points of entire model less then 4096 points?

**Comment by yulequan** [comment]
1. In my experiment, we divide 100 patches from each mesh. The seed vertex point of each patch is randomly chosen from the whole vertex of the mesh. 
2. Since the patches are represented as mesh, we can extract an arbitrary number of points from each patch.

**Comment by yo-ting-shieh** [comment]
thanks for your reply, may i ask about some question about modelnet_data_prep.py?
1. what is the order of your execution? I wander know what should i do if i have an obj model, and i need to packaged it into hdf5 file for training with your Net.
2. If there is any written function to dividing models into small patches, and sampling 4096 points even if the patch's points less then 4096?

**Comment by yulequan** [comment]
Hi, @yo-ting-shieh 

I have added the mesh segment and Poisson sampling code in the `prepare_data` folder.

**Comment by yo-ting-shieh** [comment]
Really thanks for releasing your code.

If the segmentation is incomplete, will it affect the training result?
I mean that my param are patch number = 100,radius = 50.0, but someplace still not contain in whole model.

**Comment by yulequan** [comment]
Maybe you can extract more patches.

**Comment by yo-ting-shieh** [comment]
haha, 
So, the more complete patches is, the better result ?
thanks for reply~

**Comment by yo-ting-shieh** [comment]
@yulequan  can Pdsampling find normals?
It couldn't work because of the file not contain normal.
I did MeshSegmentation first to generate .off, then Pdsampling to generate .xyz

**Comment by ptxaxx** [comment]
@yulequan @yo-ting-shieh
Hi！
 I have a point cloud data in txt format, use meshlab to generate mesh and save as .off format，When I use my own .off file for MeshSegmentation, I encountered some problems:
![image](https://user-images.githubusercontent.com/94749768/196436315-237a7986-5601-46a7-9ca1-3cf802ac2308.png)
Hope to get your help！

**Comment by kangya998** [comment]
> Hi！
I have compiled MeshSegment using vs2017 but  getting a lot of undeclared errors like (“vertex_size”: 找不到标识符), can you share the vs version and the exact implementation details, would appreciate your help!

**Comment by kangya998** [comment]
> @yulequan @yo-ting-shieh Hi！ I have a point cloud data in txt format, use meshlab to generate mesh and save as .off format，When I use my own .off file for MeshSegmentation, I encountered some problems: ![image](https://user-images.githubusercontent.com/94749768/196436315-237a7986-5601-46a7-9ca1-3cf802ac2308.png) Hope to get your help！
Would you like to share your experience of compiling and running MeshSegmentation?
