### ISSUE TITLE
NotFoundError: /home/haoch/Documents/PU_Net/code/tf_ops/CD/tf_nndistance_so.so

### ISSUE THREAD

**Issue by heng94** [yulequan/PU-Net#9]
Hi ,
When I ran the code   python main.py --phase test --log_dir ../model/generator2_new6 
it gave the error like this:
tensorflow.python.framework.errors_impl.NotFoundError: /home/haoch/Documents/PU_Net/code/tf_ops/CD/tf_nndistance_so.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

I have compiled every tf_xxx_compile.sh in other subfolder and it successed .ssssssss
There is no file named tf_xxx_compile.sh in the subfolder ,but there is a .so file and it seems that it does not work ! I would be very grateful if you give me some suggestions ! Thanks

**Comment by jaymefosa** [comment]
For another code base I had the same _ZTIN10 error and their advice was to compile the code directly using this repository, however when I try to compile the nndistance_so I get an error:

```
make: Circular tf_nndistance_g.cu <- tf_nndistance_g.cu.o dependency dropped.
make: Nothing to be done for 'all'.
```
Here is the modified SH file, is there an obvious issue?

```
nvcc = /usr/local/cuda-9.0/bin/nvcc
cudalib = /usr/local/cuda-9.0/lib64/
tensorflow = /home/fosa/anaconda3/envs/newTensor/lib/python3.5/site-packages/tensorflow/include

all: tf_nndistance_so.so render_balls_so.so
.PHONY : all

tf_nndistance_so.so: tf_nndistance_g.cu.o tf_nndistance.cpp
	g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I $(tensorflow) -lcudart -L $(cudalib) -O2 

tf_nndistance_g.cu.o: tf_nndistance_g.cu
	$(nvcc) -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o tf_nndistance_g.cu.o tf_nndistance_g.cu -I $(tensorflow) -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2

render_balls_so.so: render_balls_so.cpp
	g++ -std=c++11 render_balls_so.cpp -o render_balls_so.so -shared -fPIC -O2 

```

**Comment by yulequan** [comment]
Hi @HanochZzhou , I think you need to compile the code directly without using the provided .so file. This is no "tf_XXX_compile.sh" in the "CD" folder, you should modify the makefile and use make.

@jaymefosa , what is your tf version? My suggestion is first "removing the XX.cu.o" file from the folder and then "make".  If your tf version >1.3, you should modify the makefile according to the installation (that is add TF_INC=$(XXXX), TF_LIB=$(XXXX)).

**Comment by heng94** [comment]
@jaymefosa here is my SH file in "emd" subfolder:
echo 'nvcc'
/usr/local/cuda-8.0/bin/nvcc tf_auctionmatch_g.cu -o tf_auctionmatch_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_30 
echo 'g++'

TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

g++ -std=c++11 tf_auctionmatch.cpp tf_auctionmatch_g.cu.o -o tf_auctionmatch_so.so -shared -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -I /home/lqyu/software/anaconda2/lib/python2.7/site-packages/tensorflow/include  -I /usr/local/cuda-8.0/include -lcudart -L /usr/local/cuda-8.0/lib64/ -O2 -I $TF_INC -I$TF_INC/external/nsync/public/ -L$TF_LIB -ltensorflow_framework

it did work .I think it can help you ! and my tf version =1.4 ,you should check it !

And , I successed finally  !   haha ~~~~

you just modify you makefile as follow:

nvcc = /usr/local/cuda-8.0/bin/nvcc
cudalib = /usr/local/cuda-8.0/lib64/
tensorflow1 = /usr/local/lib/python2.7/dist-packages/tensorflow/include/
tf2=/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/eigen_archive/
tf3=/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public/
tf_lib=/usr/local/lib/python2.7/dist-packages/tensorflow 
all: tf_nndistance_so.so render_balls_so.so
.PHONY : all

tf_nndistance_so.so: tf_nndistance_g.cu.o tf_nndistance.cpp
	g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I $(tensorflow1) -I $(tf2) -I $(tf3)  -lcudart -L $(cudalib) -L $(tf_lib) -ltensorflow_framework -O3 -D_GLIBCXX_USE_CXX11_ABI=0

tf_nndistance_g.cu.o: tf_nndistance_g.cu
	$(nvcc) -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o tf_nndistance_g.cu.o tf_nndistance_g.cu -I $(tensorflow1) -I $(tf2) -I $(tf3) -03 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O3

render_balls_so.so: render_balls_so.cpp
	g++ -std=c++11 render_balls_so.cpp -o render_balls_so.so -shared -fPIC -O2 -D_GLIBCXX_USE_CXX11_ABI=0


use make  and you should delete .so file  before using make , finally you will get tow .so file .That's what we want !

@yulequan Thanks for your advice !

**Comment by jaymefosa** [comment]
@yulequan @HanochZzhou Thank you both very much! By using a format almost the same as HanochZzhou's I can confirm that it compiles and works for Tensorflow 1.10 and Cuda 9.0 !

I think -L$TF_LIB -ltensorflow_framework was the missing key, and keeping the "-D_GLIBCXX_USE_CXX11_ABI=0 " line. Some other advice in similar circumstances was to delete it

**Comment by HanochZzhou** [comment]
Hi 
I want to get the visualized result ,so I modified the code .In line 190  of main.py , I set 'show=True ',but there are a lot of errors in function "draw_point_cloud",which is in line 100 of pc_til.py .So could you please teach me how to show the impressive result with picture ?

**Comment by heng94** [comment]
Hi 
I want to get the visualized result ,so I modified the code .In line 190  of main.py , I set 'show=True ',but there are a lot of errors in function "draw_point_cloud",which is in line 100 of pc_til.py .So could you please teach me how to show the impressive result with picture ?

**Comment by yulequan** [comment]
Hi, what is your error information?

**Comment by heng94** [comment]
I didn't modify any other code except 'show=True',
First,
  File "/home/haoch/Documents/PU_Net/code/utils/pc_util.py", line 142, in draw_point_cloud
    points = points[zorder, :]
IndexError: index 2 is out of bounds for axis 0 with size 1

Then,I commented it and it came again,
  File "/home/haoch/Documents/PU_Net/code/utils/pc_util.py", line 153, in draw_point_cloud
    xc = int(np.round(xc))
TypeError: only size-1 arrays can be converted to Python scalars

I think it's the problem of Matrix format .

**Comment by yulequan** [comment]
Hi @HanochZzhou, I find the reason. You need to change input[:,0:3] to input[0, :,0:3] in line240 of main.py

**Comment by heng94** [comment]
@yulequan That's great ! Thank you very much !

**Comment by jialancong** [comment]
@jaymefosa Hi, I use HanochZzhou's makefile format but I still failed. I would be very grateful if you can provide your makefile. Thank you !
